import React, { useState } from 'react';

// v0 scaffold for: Compliance-readiness simulator that runs mock audits and prioritizes fixes
// Generated by batch_00 audit. Wire to real API; v0 calls /api/cf-compliance-readiness-simulator-that-runs/run.

export default function ComplianceReadinessSimulatorThatRunsPage() {
  const [input, setInput] = useState<string>('');
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  async function run() {
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const token = (typeof localStorage !== 'undefined') ? localStorage.getItem('token') : null;
      const res = await fetch('/api/cf-compliance-readiness-simulator-that-runs/run', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ input }),
      });
      setResult(await res.json());
    } catch (e: any) {
      setError(e?.message || 'Unknown error');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div style={{ padding: '2rem', maxWidth: '900px', margin: '0 auto' }}>
      <h1 style={{ fontSize: '1.5rem', fontWeight: 600 }}>Compliance-readiness simulator that runs mock audits and prioritizes fixes</h1>
      <p style={{ color: '#666', marginBottom: '1rem' }}>v0 scaffold.</p>
      <textarea
        value={input}
        onChange={(e) => setInput(e.target.value)}
        style={{ width: '100%', height: '160px', padding: '12px', border: '1px solid #ddd', borderRadius: '6px', fontFamily: 'monospace' }}
      />
      <div style={{ marginTop: '12px' }}>
        <button onClick={run} disabled={loading} style={{ background: '#0070f3', color: '#fff', padding: '10px 18px', border: 'none', borderRadius: '6px' }}>
          {loading ? 'Running…' : 'Run'}
        </button>
      </div>
      {error && <pre style={{ marginTop: '16px', color: '#c00', background: '#fee', padding: '12px' }}>{error}</pre>}
      {result && <pre style={{ marginTop: '16px', background: '#f7f7f7', padding: '12px', overflow: 'auto', maxHeight: '480px' }}>{JSON.stringify(result, null, 2)}</pre>}
    </div>
  );
}
