import { FormEvent, useEffect, useState } from 'react';
import { auth, governance } from '../services/api';

type User = { id: string; name: string; email: string; role: string };
type Source = { id: string; source_uri: string; publisher: string; source_version: string; jurisdiction: string };
type Policy = { id: string; policy_key: string; version: number; status: string; reviewer_id: string; legal_hold: boolean };
const next: Record<string,string[]> = { draft:['review'], review:['approval_pending','changes_requested'], changes_requested:['review'], approval_pending:['approved','rejected'], approved:['released'] };
async function digest(value: string) { const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return [...new Uint8Array(bytes)].map(byte => byte.toString(16).padStart(2,'0')).join(''); }

export default function GovernanceWorkflow() {
  const [users,setUsers]=useState<User[]>([]); const [sources,setSources]=useState<Source[]>([]); const [policies,setPolicies]=useState<Policy[]>([]); const [selected,setSelected]=useState(''); const [detail,setDetail]=useState<any>(null); const [message,setMessage]=useState('');
  const [source,setSource]=useState({source_uri:'https://',publisher:'',jurisdiction:'',effective_at:'',source_version:'',content:''});
  const [policy,setPolicy]=useState({policy_key:'',body:'',reviewer_id:''});
  const [evidence,setEvidence]=useState({source_version_id:'',locator:'',obligation:'',owner_id:'',deadline:'',risk_rating:'high'});
  async function load(){const [u,s,p]=await Promise.allSettled([auth.users(),governance.sources(),governance.policies()]);if(u.status==='fulfilled')setUsers(u.value as User[]);if(s.status==='fulfilled')setSources(s.value as Source[]);if(p.status==='fulfilled')setPolicies(p.value as Policy[]);}
  useEffect(()=>{void load();},[]); useEffect(()=>{if(selected)governance.policy(selected).then(setDetail).catch(e=>setMessage(e.message));},[selected]);
  async function act(work:()=>Promise<any>){setMessage('');try{await work();await load();if(selected)setDetail(await governance.policy(selected));setMessage('Saved to the governed record.');}catch(error){setMessage(error instanceof Error?error.message:'Request failed');}}
  async function ingest(event:FormEvent){event.preventDefault();await act(async()=>governance.ingestSource({...source,content_digest:await digest(source.content),effective_at:new Date(source.effective_at).toISOString(),provenance:{capture:'manual-verified',captured_at:new Date().toISOString()}}));}
  async function createPolicy(event:FormEvent){event.preventDefault();await act(async()=>governance.createPolicy({policy_key:policy.policy_key,body_digest:await digest(policy.body),reviewer_id:policy.reviewer_id}));}
  async function link(event:FormEvent){event.preventDefault();if(!selected)return;await act(()=>governance.addEvidence(selected,{...evidence,deadline:new Date(evidence.deadline).toISOString()}));}
  return <div className="container" style={{maxWidth:1200}}><h1 className="h1">Governed policy release</h1><p>Versioned sources, cited obligations, deterministic evaluation, independent approval, retention and immutable decisions.</p>{message&&<div className={message.startsWith('Saved')?'success':'error'}>{message}</div>}
    <div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:16,marginTop:20}}>
      <form className="card col" onSubmit={ingest}><h2>1. Capture source version</h2>{(['source_uri','publisher','jurisdiction','effective_at','source_version','content'] as const).map(key=><label className="col" key={key}><span className="label">{key.replace(/_/g,' ')}</span>{key==='content'?<textarea required value={source[key]} onChange={e=>setSource({...source,[key]:e.target.value})}/>:<input required type={key==='effective_at'?'datetime-local':'text'} value={source[key]} onChange={e=>setSource({...source,[key]:e.target.value})}/>}</label>)}<button>Store immutable source</button></form>
      <form className="card col" onSubmit={createPolicy}><h2>2. Create policy version</h2><label className="col"><span className="label">Policy key</span><input required value={policy.policy_key} onChange={e=>setPolicy({...policy,policy_key:e.target.value})}/></label><label className="col"><span className="label">Policy body</span><textarea required value={policy.body} onChange={e=>setPolicy({...policy,body:e.target.value})}/></label><label className="col"><span className="label">Independent reviewer</span><select required value={policy.reviewer_id} onChange={e=>setPolicy({...policy,reviewer_id:e.target.value})}><option value="">Choose reviewer</option>{users.map(user=><option key={user.id} value={user.id}>{user.name} ({user.role})</option>)}</select></label><button>Create version</button></form>
    </div>
    <section className="card" style={{marginTop:16}}><h2>3. Select governed policy</h2><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a policy</option>{policies.map(item=><option key={item.id} value={item.id}>{item.policy_key} v{item.version} — {item.status}</option>)}</select></section>
    {selected&&<div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:16,marginTop:16}}><form className="card col" onSubmit={link}><h2>4. Cite obligation</h2><select required value={evidence.source_version_id} onChange={e=>setEvidence({...evidence,source_version_id:e.target.value})}><option value="">Source version</option>{sources.map(item=><option key={item.id} value={item.id}>{item.publisher} {item.source_version}</option>)}</select><input required placeholder="Exact clause / page locator" value={evidence.locator} onChange={e=>setEvidence({...evidence,locator:e.target.value})}/><textarea required placeholder="Testable obligation" value={evidence.obligation} onChange={e=>setEvidence({...evidence,obligation:e.target.value})}/><select required value={evidence.owner_id} onChange={e=>setEvidence({...evidence,owner_id:e.target.value})}><option value="">Obligation owner</option>{users.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select><input required type="datetime-local" value={evidence.deadline} onChange={e=>setEvidence({...evidence,deadline:e.target.value})}/><select value={evidence.risk_rating} onChange={e=>setEvidence({...evidence,risk_rating:e.target.value})}>{['low','medium','high','critical'].map(risk=><option key={risk}>{risk}</option>)}</select><button>Link immutable evidence</button></form>
      <section className="card col"><h2>5. Evaluate and decide</h2><p>Status: <strong>{detail?.status||'loading'}</strong></p><p>{detail?.evidence?.length||0} citation(s), {detail?.evaluations?.length||0} evaluation(s), {detail?.decisions?.length||0} immutable decision(s)</p><button onClick={()=>act(()=>governance.evaluate(selected,'Every release citation resolves to an authoritative source and every obligation has an owner, deadline, and bounded risk rating.'))}>Run release evaluation</button>{(next[detail?.status]||[]).map(target=><button key={target} className="secondary" onClick={()=>act(()=>governance.transition(selected,target,`Accountable decision to move policy to ${target}`))}>Move to {target}</button>)}<button className="secondary" onClick={()=>act(()=>governance.legalHold(selected))}>Apply irreversible legal hold</button><button className="secondary" onClick={()=>act(async()=>{const result:any=await governance.auditExport();setMessage(`Audit export verified: ${result.records.length} decisions, SHA-256 ${result.sha256}`);})}>Verify audit export</button></section></div>}
  </div>;
}
