"""v0 scaffold for: Evidence assistant with OCR

Generated by batch_00 audit. Wire LLM, vendor APIs, or DB as needed.
"""
from typing import Optional
from fastapi import APIRouter, Depends
from pydantic import BaseModel

from auth import get_current_user
from database import get_db
from models import User

router = APIRouter(prefix="/api/evidence-assistant", tags=["evidence-assistant"])


class RunRequest(BaseModel):
    payload: Optional[dict] = None


@router.get("/health")
def health(current_user: User = Depends(get_current_user)):
    return {"feature": "evidence-assistant", "status": "ok", "version": "v0"}


@router.post("/run")
def run(req: RunRequest, current_user: User = Depends(get_current_user)):
    # TODO: wire LLM client (anthropic/openrouter) or vendor integration
    return {
        "success": True,
        "result": {
            "feature": "evidence-assistant",
            "stage": "scaffold",
            "received_keys": list((req.payload or {}).keys()),
            "note": "Implementation pending. See feature suggestion: Evidence assistant with OCR",
        },
    }


@router.get("/history")
def history(current_user: User = Depends(get_current_user)):
    # TODO: persist + query from DB. Returning empty list for v0.
    return {"items": [], "note": "Persistence not wired in v0"}
