"""v0 scaffold for: No outbound webhooks
Generated by batch_00 audit gaps. Wire LLM, vendor APIs as needed.
TODO: configure credentials
"""
import os
import json
from typing import Any

from fastapi import APIRouter, Depends, Request

try:
    from auth import get_current_user
except Exception:  # pragma: no cover
    def get_current_user():
        return {"id": "anonymous"}

router = APIRouter(prefix="/api/gap-outbound-webhooks", tags=["gap-outbound-webhooks"])


async def _call_openrouter(prompt: str) -> Any:
    api_key = os.getenv("OPENROUTER_API_KEY")
    if not api_key:
        return {"stub": True, "note": "OPENROUTER_API_KEY not set. v0 stub response."}
    try:
        import httpx  # type: ignore
        async with httpx.AsyncClient(timeout=30) as client:
            r = await client.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers={
                    "Content-Type": "application/json",
                    "Authorization": f"Bearer {api_key}",
                },
                json={
                    "model": os.getenv("OPENROUTER_MODEL", "anthropic/claude-3.5-sonnet"),
                    "messages": [
                        {"role": "system", "content": "You are an assistant for the feature: No outbound webhooks."},
                        {"role": "user", "content": prompt},
                    ],
                },
            )
            if r.status_code != 200:
                return {"error": f"OpenRouter HTTP {r.status_code}"}
            data = r.json()
            return {"choices": data.get("choices"), "model": data.get("model")}
    except Exception as exc:  # pragma: no cover
        return {"error": str(exc)}


@router.get("/health")
def health():
    return {"feature": "outbound-webhooks", "status": "ok", "version": "v0", "kind": "gap"}


@router.post("/run")
async def run(request: Request, _user: Any = Depends(get_current_user)):
    try:
        payload = await request.json()
    except Exception:
        payload = {}
    prompt = payload.get("input") if isinstance(payload, dict) else None
    if not isinstance(prompt, str):
        prompt = json.dumps(payload)
    ai_result = await _call_openrouter(prompt)
    return {
        "success": True,
        "result": {
            "feature": "outbound-webhooks",
            "title": "No outbound webhooks",
            "receivedKeys": list(payload.keys()) if isinstance(payload, dict) else [],
            "ai": ai_result,
        },
    }
